version: '3.8'

services:
  postgres:
    image: postgis/postgis
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: project1
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      PGADMIN_USER: admin
      PGADMIN_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/docker/volumes/postgres:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/front.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    network_mode: host
    command: npm run start

  # backend:
  #   build:
  #     context: ./db_project
  #     dockerfile: ../docker/back.Dockerfile
  #   command: sleep 10000 #python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ./db_project:/app
  #     - ./venv/lib/python3.11/site-packages:/usr/local/lib/python3.11/site-packages
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://myuser:mypassword@db:5432/project1
