version: "3.8"
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.retention.time=10y"
    volumes:
      - ./docker/prometheus/prometheus.docker.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml
      - ./docker/volumes/prometheus_data:/prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana:8.2.6
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./docker/volumes/grafana_data:/var/lib/grafana
      - ./docker/grafana/datasources/datasource.docker.yaml:/etc/grafana/provisioning/datasources/datasource.docker.yaml
      - ./docker/grafana/dashboards/:/etc/grafana/provisioning/dashboards/
    external_links:
      - prometheus

  # still need to implement elasticsearch, but keeping this here for later
  # elasticsearch_exporter:
  #   container_name: elasticsearch_exporter
  #   image: prometheuscommunity/elasticsearch-exporter:latest
  #   command:
  #     - "--es.uri=http://db_elasticsearch:9200"
  #   restart: always
  #   ports:
  #     - "9210:9114"
  #   depends_on:
  #     - db_elasticsearch
  # postgres_exporter:
  #   container_name: postgres-exporter
  #   image: prometheuscommunity/postgres-exporter
  #   environment:
  #     DATA_SOURCE_NAME: "postgresql://myuser:mypassword@postgres_db:5432/project1?sslmode=disable"
  #   ports:
  #     - "9187:9187"
