version: "3.8"
services:
  logstash:
    image: logstash:8.16.3
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: kibana:8.16.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - SERVER_TIMEOUT=600000
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
      - NODE_OPTIONS=--no-experimental-fetch --openssl-legacy-provider=false --plugins=allowlist
    depends_on:
      elasticsearch:
        condition: service_healthy
