version: '3.8'

services:
  postgres:
    image: postgis/postgis
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: project1
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      PGADMIN_USER: admin
      PGADMIN_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/docker/volumes:/var/lib/postgresql/data

