apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery
          image: minikube.local/django-app:latest
          imagePullPolicy: IfNotPresent
          command: ["celery", "-A", "main", "worker", "--loglevel=info"]
          env:
            - name: CELERY_BROKER_URL
              value: "redis://redis:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis:6379/0"
