# Generated by Django 5.0.4 on 2024-04-27 16:42

import django.contrib.gis.db.models.fields
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("photo_url", models.CharField(max_length=255)),
                (
                    "coords",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("location_confirmed", models.BooleanField()),
            ],
            options={
                "db_table": "Profile",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                ("block_id", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "coords",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("radius", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                "db_table": "Block",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower_id", models.IntegerField()),
                ("followee_id", models.IntegerField()),
                ("confirmed", models.BooleanField()),
            ],
            options={
                "db_table": "Friendship",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Hood",
            fields=[
                ("hood_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "Hood",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("message_id", models.IntegerField(primary_key=True, serialize=False)),
                ("thread_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                (
                    "coords",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("body", models.TextField()),
                (
                    "datetime",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "db_table": "Message",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "notification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("to_user", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("notification_type", models.CharField(max_length=50)),
                ("thread_id", models.IntegerField(null=True)),
                ("message_id", models.IntegerField(null=True)),
                (
                    "datetime",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "db_table": "Notifications",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileBlockApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("approver_id", models.IntegerField()),
            ],
            options={
                "db_table": "ProfileBlockApproval",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                ("thread_id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("block_id", models.IntegerField(null=True)),
                ("hood_id", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "Thread",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("thread_id", models.IntegerField(null=True)),
                (
                    "datetime",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "db_table": "UserAccess",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserFollowBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
            ],
            options={
                "db_table": "UserFollowBlock",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserFollowHood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hood_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
            ],
            options={
                "db_table": "UserFollowHood",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
            ],
            options={
                "db_table": "UserThread",
                "managed": False,
            },
        ),
    ]
