# Generated by Django 5.0.4 on 2025-01-18 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notification_delete_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='to_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='friendship',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.friendship'),
            preserve_default=False,
        ),
    ]
