# Generated by Django 5.0.4 on 2025-01-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_notification_to_user_notification_friendship'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='follower',
            index=models.Index(fields=['follower', 'followee'], name='main_follow_followe_ed2c80_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['from_user', 'to_user'], name='main_friend_from_us_17690e_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['status'], name='main_friend_status_9a281a_idx'),
        ),
    ]
