# Generated by Django 5.0.4 on 2025-01-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_follower_main_follow_followe_ed2c80_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Follow',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='main_follow_followe_f8a351_idx',
            old_name='main_follow_followe_ed2c80_idx',
        ),
    ]
