# Generated by Django 5.0.4 on 2025-01-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_follower_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='follow',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.follow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accept', 'Friend Accept'), ('message', 'Message'), ('follow', 'Follow')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
