# Generated by Django 5.0.4 on 2025-01-18 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notification_follow_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.AlterField(
            model_name='notification',
            name='follow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.follow'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='friendship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.friendship'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.thread'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('FRIEND_REQUESTED', 'Friend Request'), ('FRIEND_ACCEPTED', 'Friend Accept'), ('MESSAGE', 'Message'), ('FOLLOW', 'Follow')], max_length=50),
        ),
    ]
