# Generated by Django 5.0.4 on 2025-01-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userthread_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='thread_type',
            new_name='type',
        ),
    ]
