# Generated by Django 5.0.4 on 2025-01-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_thread_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='type',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('HOOD', 'Hood')], max_length=10),
        ),
    ]
