# Generated by Django 5.0.4 on 2025-01-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_thread_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='message_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
