# Generated by Django 5.0.4 on 2025-03-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_notification_message_notification_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
