# Generated by Django 5.0.4 on 2025-03-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_user_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
