apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: minikube.local/django-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: "postgres://myuser:mypassword@postgres:5432/project1"
            - name: MONGO_URI
              value: "mongodb://mongo:27017"
            - name: CELERY_BROKER_URL
              value: "redis://redis:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis:6379/0"
          ports:
            - containerPort: 8000
