name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_DB: project1
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U myuser -d project1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

      redis:
        image: redis:latest
        ports:
          - "6379:6379"

      mongo:
        image: mongo:latest
        ports:
          - "27017:27017"
        # env:
        #   MONGO_INITDB_ROOT_USERNAME: root
        #   MONGO_INITDB_ROOT_PASSWORD: example

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backend Docker Image
        run: docker build -t backend-test -f docker/back.Dockerfile .
      - name: Wait for Services
        run: |
          for i in {1..30}; do
            nc -z localhost 5432 && nc -z localhost 27017 && break
            echo "Waiting for database services..."
            sleep 2
          done
      - name: Run Backend Tests
        run: |
          docker run --rm --network=host \
            -e POSTGRES_HOST=localhost \
            -e MONGO_HOST=localhost \
            -e REDIS_HOST=localhost \
            backend-test python manage.py test
